apiVersion: v1
kind: Service
metadata:
  name: aintern-acourse-io
  labels:
    app: aintern-acourse-io
spec:
  type: NodePort
  selector:
    app: aintern-acourse-io
  ports:
  - port: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aintern-acourse-io
  labels:
    app: aintern-acourse-io
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: aintern-acourse-io
  template:
    metadata:
      name: aintern-acourse-io
      labels:
        app: aintern-acourse-io
    spec:
      containers:
      - name: aintern-acourse-io
        image: gcr.io/acoshift-1362/aintern-acourse-io
        ports:
        - containerPort: 8080
        livenessProbe: &probe
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 5
        readinessProbe: *probe
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
